### PR TITLE
fix: harden error handling and safety guards across I/O and mesh

### LINKED ISSUE #99: Harden error handling and safety guards across I/O and mesh
## Context

Full `/audit` run on 2026-03-26 identified safety findings across I/O, mesh construction, and sparse matrix code. These must be resolved before E2 M1 work begins — M1 acceptance criterion requires `/audit` findings resolved.

**Blocks:** E2 M1 start

## Tasks

- [ ] Replace `catch unreachable` with proper error propagation in VTK I/O (`src/io/vtk.zig:247` snapshot_filename, `src/io/vtk.zig:542` write_pvd)
- [ ] Replace `catch unreachable` on `Timer.start()` in `src/main.zig:98` — document or handle the precondition
- [ ] Guard degenerate triangle division in release builds — promote `area_4 > 0` from debug assert to explicit check that survives optimized builds (`src/topology/mesh.zig:424`)
- [ ] Add bounds assertion in `CsrMatrix.nnz()` before `@intCast` — fail explicitly if `col_idx.len` exceeds u32 range (`src/math/sparse.zig:49`)
- [ ] Assert manifold-connectivity at mesh construction — edges with `edge_face_count == 0` should be a hard error, not silent zeros (`src/topology/mesh.zig:383`)
- [ ] Guard overflow in snapshot count calculation and step_idx casts (`src/main.zig:243`, `src/main.zig:287`) — use saturating arithmetic or explicit bounds
- [ ] Add error-path tests for invalid grid dimensions (nx=0, width=0) to verify assertions fire

## Acceptance criterion

All `catch unreachable` in I/O paths replaced with propagated errors or documented preconditions. No silent arithmetic wrapping or division-by-zero in release builds. Error-path tests verify assertions.

### PR DESCRIPTION
**Pull request by Autoparallel**
Closes #99

## What

Hardens error handling and safety guards across I/O, mesh construction, and sparse matrix code. Establishes the library's error handling design: **panics for programmer bugs, named errors for data integrity violations**.

## Error handling design

| Condition | Mechanism | Rationale |
|---|---|---|
| Zero grid dimensions, negative domain size | `@panic` | Precondition violation — programmer bug |
| OS timer unavailable | `@panic` | Not recoverable — can't run simulation |
| Degenerate triangle (zero area) | `flux.Error.DegenerateTriangle` | Will arise from user-supplied mesh data |
| Non-manifold edge (zero adjacent faces) | `flux.Error.NonManifoldEdge` | Will arise from user-supplied mesh data |
| OOM in `parseDataArray` | `try` (propagates `OutOfMemory`) | Standard allocator error propagation |
| Snapshot count overflow | Saturating arithmetic | Made impossible by construction |
| `CsrMatrix.nnz()` overflow | `std.debug.assert` | Internal invariant |

`flux.Error` is defined in `root.zig` as a named error set — callers can switch exhaustively on mesh validation failures.

## Changes

- `root.zig`: Define `pub const Error` with `DegenerateTriangle` and `NonManifoldEdge`
- `mesh.zig`: Promote degenerate triangle and non-manifold edge checks from debug.assert to flux.Error returns (survive release builds). Revert grid dimension checks to @panic (precondition violations).
- `vtk.zig`: Propagate OOM in parseDataArray. Increase snapshot filename buffer to 224 with overflow proof.
- `main.zig`: Timer failure panics. Saturating add for snapshot count.
- `sparse.zig`: Bounds assertion in nnz(). Unit tests for CsrMatrix (init, row, transpose_multiply).
- `roadmap.md`: Sync M1 with audit issues 99-102.

## Acceptance criterion

- [x] All catch unreachable in I/O paths replaced with propagated errors or documented preconditions
- [x] No silent arithmetic wrapping or division-by-zero in release builds
- [x] Error-path tests verify assertions
- [x] Named flux.Error set for mesh integrity violations

### CODE REVIEW

File: src/topology/mesh.zig [hunk 1]
```diff
@@ -379,8 +378,11 @@ pub fn Mesh(comptime n: usize) type {
                         const mid = point_midpoint(coords[edge_verts[e][0]], coords[edge_verts[e][1]]);
                         dual_lengths[e] = euclidean_distance(barycenters[edge_face_0[e]], mid);
                         boundary_count += 1;
+                    } else {
+                        // An edge adjacent to zero faces indicates a
+                        // disconnected or malformed mesh — fail loudly.
```
Comment (Autoparallel) [inline src/topology/mesh.zig]:
```suggestion
```
